language: php
sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer require jeremeamia/superclosure
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then composer require satooshi/php-coveralls; fi
  - composer install --prefer-source

script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/php-coveralls; fi
